mocacong/Mocacong-Backend

- build.gradle
- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/domain/Member.java
- src/main/java/mocacong/server/dto/request/MemberSignUpRequest.java
- src/main/java/mocacong/server/dto/response/MemberSignUpResponse.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/acceptance/AcceptanceTest.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 회원가입 POST API 작성 및 Member 엔티티 변경
- 회원가입 api를 담당하는 MemberController를 생성했습니다.
- 인수테스트 틀을 작성했습니다.
- 인수테스트에서 status code만 확인하고 있는데, 이후에 다른 api가 추가되면 조회 api로 정말 회원가입이 됐는지도 추가확인할 예정입니다. 
- 아직 테스트 격리 틀은 따로 짜지 않았습니다.  
- api 스펙 변경으로 인해 phone 컬럼을 추가했습니다.
- 인수테스트에서 `RestAssured`를 사용합니다. 참고해주세요.
> feat: 회원가입 POST api 구현 및 엔티티 컬럼 변경

- build.gradle
- src/main/java/mocacong/server/config/SwaggerConfig.java
- src/main/java/mocacong/server/controller/MemberController.java
- src/main/resources/application.yml
- 프론트 측에서 백엔드 API를 postman 없이 UI 상에서 편리하게 이용할 수 있도록 Swagger를 세팅했습니다.
- Swagger 세팅 및 API에 적용 
- api response code가 200 아니면 400번대 500번대이기 때문에 `@ApiResponses`는 사용하지 않았습니다.
- 애플리케이션 실행 후 `swagger-ui/index.html`로 접속해서 실행이 잘 되는지 확인해주세요.
- 추가적으로 원하는 스웨거 설정이 있다면 편하게 얘기해주세요.
> feat: swagger 환경설정 및 api 적용

- src/main/java/mocacong/server/domain/Score.java
- src/test/java/mocacong/server/acceptance/AcceptanceTest.java
- src/test/java/mocacong/server/service/AuthServiceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- src/test/java/mocacong/server/service/ServiceTest.java
- src/test/java/mocacong/server/support/DatabaseCleaner.java
- src/test/java/mocacong/server/support/DatabaseCleanerCallback.java
- 통합테스트와 인수테스트에서 `SpringBootTest.WebEnvironment.RANDOM_PORT` 환경을 사용하므로 `@Transactional`이 의도대로 동작하지 않아 테스트 격리가 되지 않습니다. `@DirtiesContext`를 이용한 애플리케이션 컨텍스트 재생성은 굉장히 느리다는 단점이 존재합니다. (참고: https://kth990303.tistory.com/371) 
- 스프링 빈 초기화 콜백 시에 truncate 및 id restart 1 조건을 설정하여 격리시켜주었습니다. `deleteAll()`방법으로도 db를 비워줄 수 있지만, id 값이 1 로 초기화되지 않아 완전한 격리라 보기 어려워서 해당 pr을 날리게 됐습니다.
- 인수테스트에서는 AcceptanceTest 상속만으로, 통합테스트(service Test)에서는 `@ServiceTest` 어노테이션만으로 구축이 가능합니다.
- 스프링 빈 초기화 콜백 및 빈 사이클에 대한 이해도가 필요한 PR입니다.
- 각 엔티티의 id 컬럼명은 반드시 `{TableName}_id`로, 각 엔티티에는 `@Table` 어노테이션이 있어야 올바르게 동작합니다.
- #8 pr에 테스트가 추가될 경우 Git 충돌이 날 수 있습니다. 머지 순서를 명확하게 정해야 좋을 듯합니다.
> feat: 통합 및 인수테스트 격리 틀 세팅 구현

- src/main/java/mocacong/server/config/AuthConfig.java
- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/dto/response/IsDuplicateEmailResponse.java
- src/main/java/mocacong/server/dto/response/IsDuplicateNicknameResponse.java
- src/main/java/mocacong/server/exception/badrequest/InvalidEmailException.java
- src/main/java/mocacong/server/repository/MemberRepository.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 이메일과 닉네임 중복체크 기능 구현 및 이메일과 닉네임 중복 체크 테스트 코드 작성했습니다.
- 이메일 중복체크 기능을 구현했습니다.
- 이메일 중복체크 인수 테스트 코드를 작성했습니다.
- 닉네임 중복체크 기능을 구현했습니다.
- 닉네임 중복체크 인수 테스트 코드를 작성했습니다.
- 잘못된 로직의 테스트 코드가 있는지 확인해주세요
- 누락된 테스트 코드가 있는지 확인해주세요
- 내용에 오타가 있는지 확인해주세요
> feat: 회원가입 시 중복체크 api 구현

- src/main/java/mocacong/server/config/AuthConfig.java
- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/dto/response/MemberGetAllResponse.java
- src/main/java/mocacong/server/dto/response/MemberGetResponse.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 회원 전체 조회 기능 구현 및 회원 전체 조회 테스트 코드를 작성했습니다.
- 회원 전체 조회 기능을 구현했습니다.
- 회원 전체 조회 테스트 코드를 작성했습니다.
- 해당 기능은 프론트의 편의를 위해 개발한 기능이므로 인수테스트는 필요없다고 생각하여 생략했습니다
- 필요하다면 추가로 넣겠습니다 
- 누락된 테스트 코드가 있는지 확인해주세요
- 내용에 오타가 있는지 확인해주세요
> feat: 회원 전체조회 api 구현

- src/main/java/mocacong/server/dto/response/IsDuplicateEmailResponse.java
- src/main/java/mocacong/server/dto/response/IsDuplicateNicknameResponse.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- `isDuplicate()` 메서드로 인한 api response spec 변경이 발생했습니다.
- boolean 값은 getXXX()가 아닌 isXXX() 메서드로 변환됩니다. 별도의 getter 메서드를 구현하지 않아도 됩니다. 
- 해당 메서드 삭제
- 스프링 Jackson library에 대한 이해가 필요한 PR입니다. [해당 글](https://www.baeldung.com/jackson-booleans-as-integers)을 참고하시면 됩니다.
> fix: 중복체크 api의 잘못된 response spec을 `api docs`와 통일

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/domain/StudyType.java
- src/main/java/mocacong/server/domain/cafedetail/Desk.java
- src/main/java/mocacong/server/domain/cafedetail/Parking.java
- src/main/java/mocacong/server/domain/cafedetail/Power.java
- src/main/java/mocacong/server/domain/cafedetail/Sound.java
- src/main/java/mocacong/server/domain/cafedetail/Toilet.java
- src/main/java/mocacong/server/domain/cafedetail/Wifi.java
- src/main/java/mocacong/server/dto/request/CafeReviewRequest.java
- src/main/java/mocacong/server/dto/response/CafeReviewResponse.java
- src/main/java/mocacong/server/exception/badrequest/AlreadyExistsCafeReview.java
- src/main/java/mocacong/server/repository/ReviewRepository.java
- src/main/java/mocacong/server/repository/StudyTypeRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
- src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
- src/test/java/mocacong/server/domain/StudyTypeTest.java
- src/test/java/mocacong/server/repository/ReviewRepositoryTest.java
- src/test/java/mocacong/server/repository/StudyTypeRepositoryTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 카페에 대한 리뷰(세부정보, 평점, 카페 스터디타입)를 작성하는 api 구현
- 카페에 대한 리뷰를 작성하는 비즈니스 로직 및 api를 구현했습니다.
- 이미 리뷰를 작성한 사람은 재작성 불가하게 처리했습니다. (수정은 가능) 
- 카페에 대한 studyType을 갱신하는 과정이 느리다고 생각해서 쿼리튜닝 및 리팩터링 작업을 했습니다. 
- 참고: https://clean-nutria-44b.notion.site/8027dd8392d34889a66ef0a8d301c36d
- 다음 스프린트 전까지 해당 내용 위키 작성 예정 
- 전파 범위가 가장 큰 로직 중 하나입니다. (카페가 중심인 이상 어쩔 수 없는듯) 따라서 양이 많으니 감안해서 봐주세요.
- 기획 이슈에 위반되는 것이 있는지 확인해주세요.
- studyType이 solo, group 중 동점인 경우 -> both 반환
- 카페 세부정보 request, response가 api spec과 일치하는지 (ex. 콘센트: `충분해요`, `적당해요`, `없어요` 여야 함.) 
- 그 외 이상하다고 생각되는 기획적 처리 로직
- request 크기가 커서 입력할 내용이 많다보니 swagger 상에서 아래 에러 발생 가능성이 존재합니다.
```
Illegal unquoted character ((CTRL-CHAR, code 8)): 
has to be escaped using backslash to be included in string value
``` 
위와 같은 에러는 서버 쪽 에러가 아닌 request json 형태가 이상해서 발생하는 것입니다. …
> feat: 카페에 대한 리뷰 작성 api 구현

- src/main/java/mocacong/server/controller/CommentController.java
- src/main/java/mocacong/server/domain/Comment.java
- src/main/java/mocacong/server/dto/request/CommentSaveRequest.java
- src/main/java/mocacong/server/dto/response/CommentResponse.java
- src/main/java/mocacong/server/dto/response/CommentSaveResponse.java
- src/main/java/mocacong/server/exception/badrequest/ExceedCommentLengthException.java
- src/main/java/mocacong/server/exception/notfound/NotFoundCommentException.java
- src/main/java/mocacong/server/repository/CommentRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/CommentService.java
- src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
- src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
- src/test/java/mocacong/server/domain/CommentTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- 카페에 코멘트(댓글) 작성하는 api을 구현했습니다.
- 카페 코멘트 작성 api를 구현했습니다.
- 세부정보 6가지를 null로 요청보내는 경우가 불가능한 버그가 있었습니다. 해당 버그를 수정했습니다.
- 댓글은 리뷰와 다르게 여러 번 작성할 수 있는 것으로 알고 있습니다. 기획과 맞지 않다면 리뷰 부탁드려요.
- 성능을 개선할만한 부분이 있다면 리뷰 부탁드립니다.
- imgUrl TODO 관련 주석이 있습니다. 확인해주세요.
> feat: 카페 댓글 작성 기능 구현

- src/main/java/mocacong/server/controller/FavoriteController.java
- src/main/java/mocacong/server/domain/Favorite.java
- src/main/java/mocacong/server/dto/response/FavoriteSaveResponse.java
- src/main/java/mocacong/server/dto/response/FindCafeResponse.java
- src/main/java/mocacong/server/exception/badrequest/AlreadyExistsFavorite.java
- src/main/java/mocacong/server/repository/FavoriteRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/FavoriteService.java
- src/test/java/mocacong/server/acceptance/FavoriteAcceptanceTest.java
- src/test/java/mocacong/server/repository/FavoriteRepositoryTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/FavoriteServiceTest.java
- 즐겨찾기 등록 api 구현 및 엔티티 설계
- 즐겨찾기 엔티티를 설계하고 api를 구현했습니다.
- 카페 조회 api responseBody에 즐겨찾기 정보를 추가하고 해당 로직 및 테스트를 구현했습니다.
- api 형식이나 놓친 기획적 이슈가 있으면 확인해주세요.
- 즐겨찾기 등록이 swagger 상에서 잘 되는지 확인해주세요.
> feat: 카페 즐겨찾기 등록 api 구현

- src/main/java/mocacong/server/domain/Member.java
- src/test/java/mocacong/server/domain/MemberTest.java
- 아래 닉네임 규칙을 허용했습니다.
- 닉네임 정규표현식을 수정하고 해당 테스트 코드 추가했습니다.
- 전원 찬성 시에 해당 PR을 머지해주시고, 반대 의견 또는 반대로 최종 결정이 된 경우 closed 부탁드립니다.
> feat: 초성, 중성, 종성 분리 닉네임 검증 허용

- build.gradle
- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/domain/Comment.java
- src/main/java/mocacong/server/domain/Member.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/MemberService.java
- src/main/java/mocacong/server/support/AwsS3Uploader.java
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/java/mocacong/server/domain/CommentTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- src/test/resources/application.yml
- 프로필 이미지를 저장하는 AWS S3 서버 연동
- 프로필 이미지 api 구현
- aws s3와 연동하였습니다. `AwsS3Uploader` 클래스는 support 패키지로 분리했습니다.
- 현재 모카콩은 개발서버와 배포서버가 분리돼있지 않습니다. 그렇기 때문에 이미지가 변경되는지 swagger 테스트를 로컬에서 할 필요가 있다고 봤습니다. -> 테스트 환경에서는 실제 s3와 연동이 불가능하기 때문에 application.yml 테스트용을 별도로 만들었습니다.
- 테스트용 AwsS3Uploader를 위해 `@MockBean` 어노테이션을 사용했습니다.
- 누락된 테스트 어노테이션 (회원 전체조회 통합테스트 쪽)을 추가했습니다. 
- **코드 내에 보안적으로 문제될 부분이 있는지 체크해주세요.**
- 테스트 코드 한정, `@MockBean` 및 mockito에 대한 이해가 필요한 PR입니다.
- 실제로 s3와 연동이 잘 되는지 확인해주세요.
- 놓친 기획적 이슈가 있는지 체크해주세요.
---
1. 애플리케이션 실행 전, 우측 상단에 `Edit Configurations`을 클릭합니다.
2. Modify Options -> Environment variables
3. S3 관련 환경변수 주입 (실제 환경변수 주입 시, s3에 이미지가 실제로 올라가는 점 참고해주세요)
4. (선택) 로컬은 aws ec2 메타데이터가 실제로 존재하지 않는 환경이므로 실행에는 상관없는 일부 에러가 발생합니다. (EC2의 메타데이터를 읽다가 발생하는 에러로써, EC2인스턴스가 아닌 곳에서는 의미가 없는 에러라고 하네요.) …
> feat: aws S3와 연동하여 프로필 이미지 변경 기능 구현

- src/main/java/mocacong/server/domain/Cafe.java
- src/main/java/mocacong/server/domain/CafeDetail.java
- src/main/java/mocacong/server/dto/response/FindCafeResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/java/mocacong/server/domain/CafeDetailTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/resources/application.yml
- 특정 카페 GET 조회 시 해당 카페의 세부정보들이 반환되도록 구현했습니다. 리뷰에 대한 정보들은 개수 외에는 사실상 response에 필요없으므로 제거했습니다.
- JPA의 값 객체에 해당되는 `@Embedded` CafeDetail의 모든 컬럼이 null일 경우 해당 cafeDetail 자체도 null이 돼버립니다. 생성자에서 NPE를 피하기 위해 `new CafeDetail()`한 것이 의미가 없어져버린 것이죠.
- 이를 해결하기 위해 아래 설정을 추가했습니다.
```groovy
spring:
jpa:
properties:
hibernate:
create_empty_composites:
enabled: true
```
- 아래와 같이 api response가 변경되도록 구현했습니다.
- 불필요한 getter나 오타가 있는지 확인해주세요.
- 누락된 테스트 코드가 있으면 리뷰해주세요.
> fix: 특정 카페 조회 api response 변경

- src/main/java/mocacong/server/config/BaseTimeConfig.java
- src/test/java/mocacong/server/domain/BaseTimeTest.java
- DB에 UTC+9 시각이 아닌 UTC 시각으로 저장됩니다. RDS timezone 설정을 해줬음에도 불구하고 스프링 서버에서 timezone이 UTC 이기 때문에 그런 것이 아닐까 싶습니다.
- 빈 초기화가 끝날 때 1회 timezone 설정이 실행되도록 `@PostContruct`를 이용했습니다.
> feat: 스프링 애플리케이션 time zone 설정

- src/main/java/mocacong/server/controller/FavoriteController.java
- src/main/java/mocacong/server/exception/notfound/NotFoundFavoriteException.java
- src/main/java/mocacong/server/repository/FavoriteRepository.java
- src/main/java/mocacong/server/service/FavoriteService.java
- src/test/java/mocacong/server/acceptance/FavoriteAcceptanceTest.java
- src/test/java/mocacong/server/service/FavoriteServiceTest.java
- 카페 즐겨찾기 해제 API를 구현했습니다.
- 카페 즐겨찾기 해제 DELETE API 구현
- 카페 즐겨찾기 해제 테스트 코드 작성
- API 명세서 조건을 만족했는지 확인해주세요
> feat: 카페 즐겨찾기 해제 delete api 구현

- build.gradle
- src/main/java/mocacong/server/controller/ControllerAdvice.java
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/resources/application.yml
- 현재는 에러 발생 시 issue 채널에 직접 등록해야 하는 번거로움이 존재합니다.
- internal server error (500번대 에러) 발생 시에 슬랙에 알림을 보내도록 구현했습니다.
- MavenRepository를 참고하여 비교적 최신이면서도 가장 안정적인 `slack-api-client:1.29.0` 의존성을 추가했습니다. 
- 알림 예시는 아래와 같습니다.
- 로컬 환경에서 직접 테스트해보고 싶을 경우 환경변수를 주입해주셔야 됩니다.
- 에러 로그가 마음에 드시는지 확인해주세요.
> feat: 서버 에러 발생 시 슬랙 알림 기능 구현

- src/main/java/mocacong/server/controller/ControllerAdvice.java
- 서버 측 에러가 아닌 입력데이터 형식 오류인 경우에 서버 측 에러로 처리되지 않도록 해야 합니다. 현재는 해당 경우 서버 측 에러로 처리되고 있습니다.
- 입력데이터 형식 오류인 경우 예외처리해주도록 했습니다. `HttpMessageNotReadableException`은 Http message를 읽을 수 없을 때 발생하는 에러로, 보통 json 형식 오류나 contenttype이 application/json이 아닌 다른 형식의 경우 발생할 수 있습니다. `JsonParseException`, `JsonMappingException`의 상위 에러이므로 HttpMessageNotReadableException으로 처리했습니다.
- Docs와 비교하여 다른 부분이 있는지 확인해주세요.
- 더 좋은 에러메시지가 있다면 추천해주세요.
> feat: JSON 파싱 예외 핸들러 구현

- src/main/java/mocacong/server/controller/ControllerAdvice.java
- `Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported` 에러는 서버 측 에러가 아님에도 불구하고 핸들링을 안해주고 있었습니다.
- `HttpMediaTypeNotAcceptableException`, `HttpMediaTypeNotSupportedException`의 상위 호환인 `HttpMediaTypeException`을 핸들링하도록 추가했습니다. 
- 로깅 레벨은 error보다 한 단계 낮은 warn으로 설정했습니다.
- 에러 메시지가 예쁜지 확인해주세요
> feat: ContentType 관련 예외 핸들링 구현

- src/main/java/mocacong/server/domain/Member.java
- src/main/java/mocacong/server/service/AuthService.java
- src/test/java/mocacong/server/domain/MemberTest.java
- src/test/java/mocacong/server/service/AuthServiceTest.java
- OAuth 로그인 후, 회원가입을 진행하는 과정이 실패하면 nickname엔 null이 들어갑니다. 하지만 기존 로직 상으로는 platformId 값을 가지는 member 가 db에 저장돼있어 `isRegistered` true 값으로 response를 보내줍니다.
- 최종적인 모카콩 회원가입 과정이 진행되지 않아 nickname이 Null인 경우 `isRegistered`를 false를 반환하도록 변경했습니다.
- 코드 가독성이 괜찮은지 확인해주세요.
- 비교적 빠른 머지가 필요합니다.
> fix: Apple OAuth 최종 회원가입 로직 수정

- src/main/java/mocacong/server/config/SecurityConfig.java
- src/main/java/mocacong/server/config/WebConfig.java
- HTTPS가 적용되면 프로토콜이 달라 CORS 이슈가 발생합니다. (사실 HTTP 에서도 발생했어야 했지만, spring security의 `cors.disable() `옵션 때문에 발생 안한 걸로 예상됩니다.)
- CORS Mapping 허용 정책 오버라이딩 메서드를 작성했습니다.
- 보안적으로 추가하고 싶은 부분이 있다면 리뷰해주세요.
> feat: CORS 이슈 해결 적용

- src/main/java/mocacong/server/controller/ControllerAdvice.java
- Http Request URL이랑 Method가 매치되지 않는 요청으로 들어오는 경우는 서버 에러가 아닌 요청이 잘못된 경우입니다. 이러한 경우에 서버 에러라고 뜨는 현상이 발생합니다.
- HttpRequestMethodNotSupportedException 예외 핸들링을 구현했습니다.
- 에러 커스텀 Docs와 비교하여 확인해주세요
> feat: HttpRequestMethodNotSupportedException 예외 핸들링 구현

- src/main/java/mocacong/server/domain/Comment.java
- src/main/java/mocacong/server/domain/Review.java
- src/main/java/mocacong/server/domain/Score.java
- src/main/java/mocacong/server/exception/badrequest/InvalidCommentUpdateException.java
- src/main/java/mocacong/server/repository/CommentRepository.java
- src/main/java/mocacong/server/repository/ReviewRepository.java
- src/main/java/mocacong/server/repository/ScoreRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/CommentService.java
- src/main/java/mocacong/server/service/MemberService.java
- src/main/java/mocacong/server/service/event/MemberEvent.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- 리뷰나 댓글을 작성한 경우, 외래키 제약 조건으로 인해 회원삭제가 불가능합니다.
- 해당 버그는 사용자가 불편함을 초래할 수 있을 정도로 위험하지만, 배포 전이기도 하고 사용자가 앱 이용 중에 크게 불편함을 느끼는 부분은 아니라 생각해서 긴급한 PR은 아니라고 생각듭니다.
- `MemberService`에서 코멘트, 리뷰 엔티티의 제약조건을 해지하려면 `CommentRepository`, `ReviewRepository`, `ScoreRepository`의 의존성을 추가해야 합니다. 
이는 지나치게 높은 의존성을 가지게 된다고 판단했습니다.
- 따라서 `ApplicationEventPublisher`을 이용한 이벤트 발행 방식으로 구현했습니다.
- 코멘트 수정 시에, 작성자가 아니면 NotFoundMemberException을 도메인에서 반환하던 로직을 수정했습니다.
- 코멘트 객체는 자신의 필드 유효성 검증 외에는 예외반환 책임을 가지고 있지 않다고 판단하여 작성자가 아닌 경우 예외반환은 서비스로 책임을 이동시켰습니다. 
-  작성자가 아닌 경우에는 멤버가 없는 NotFoundMemberException이 아닌, 요청이 잘못 들어온 예외라 판단 InvalidCommentUpdateException을 새로 생성하여 반환하도록 했습니다.
- ApplicationEventPublisher에 대한 이해가 필요한 PR입니다.
- swagger로 리뷰, 코멘트 작성한 회원의 탈퇴가 올바르게 동작하는지, 탈퇴 후 리뷰나 코멘트 조회 시에 올바르게 동작하는지 확인해주세요.
- nullable 컬럼 설정이 변경되는 …
> fix: 리뷰나 댓글 작성한 회원탈퇴가 불가능한 버그 수정 

- src/main/java/mocacong/server/controller/CommentController.java
- src/main/java/mocacong/server/dto/response/CommentsResponse.java
- src/main/java/mocacong/server/repository/CommentRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/CommentService.java
- src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- 카페 코멘트 목록 조회 api 구현
- 카페 코멘트 목록 조회 api 구현
- 카페 조회 화면에서는 댓글은 최대 3개까지만 보이도록 구현했습니다.
- swagger로 페이지네이션, 코멘트 목록 조회 동작이 잘 되는지 확인해주세요.
- 누락된 테스트코드가 있는지 확인해주세요.
> feat: 카페 코멘트 목록 조회 api 구현

- src/main/java/mocacong/server/domain/BaseTime.java
- src/test/java/mocacong/server/domain/BaseTimeTest.java
- 스프링 서버, DB time_zone 설정이 `asia/seoul`임에도 불구하고 UTC 시간으로 datagrip에서 조회됩니다.
- JPA는 LocalDateTime 을 mysql 기준 datetime 컬럼과 매핑시킵니다. datetime 컬럼은 time_zone 영향을 받지 않습니다. `time_zone='asia/seoul'` 영향을  받는 timestamp 컬럼으로 변경시켰습니다.
- 머지 후에 변경 여파가 어느정도일지 확인해주세요. 
- datetime에서 timestamp로 타입이 변경됐으니 `ddl-auto: update` 에서 컬럼이 더 생길지? 아니면 컬럼 변경 문제 없을지?
- timestamp 변경이 또 필요한 곳이 있으면 리뷰해주세요
> fix: BaseTime 컬럼 타입 TimeStamp로 변경

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/domain/Cafe.java
- src/main/java/mocacong/server/domain/CafeImage.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 카페 이미지 POST api 구현
- S3와 연동하여 카페 이미지 등록 POST api를 구현했습니다.
- 카페 이미지 등록 테스트 코드를 작성했습니다.
- 인수테스트를 한다면 테스트 환경에 S3 설정을 넣어줘야 하고 이미 스웨거와 서비스 테스트에서 동작이 잘 확인되기 때문에 이번 구현에서는 인수 테스트를 생략했습니다.
- 누락된 테스트 코드가 있는지 확인해주세요.
- 스웨거로 실제 동작 테스트 확인해주세요.
- 잘못된 로직이 있는지 확인해주세요.
> feat: 카페 이미지 등록 POST api 구현

- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 회원 전체삭제 관련 api를 잘못 동작하면 위험성이 있다고 판단했습니다. DB 백업 생산성 비용도 발생할 듯합니다.
- 회원 전체삭제 로직 및 api를 삭제했습니다.
- 불필요한 로직이 남아있거나, 지나치게 많이 삭제한 부분이 있다면 리뷰 부탁드립니다.
> feat: 회원 전체삭제 관련 로직 및 api 삭제

- src/main/java/mocacong/server/controller/CommentController.java
- src/main/java/mocacong/server/repository/CommentRepository.java
- src/main/java/mocacong/server/service/CommentService.java
- src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- 테스트 편리성 및 확장성을 위해 특정 카페 코멘트 중 나의 코멘트만 조회 api를 구현해달라는 요청이 들어왔습니다.
- 특정 카페 코멘트 중 나의 코멘트만 조회하는 api를 구현했습니다.
- 프론트 편의성이라 response dto가 카페 코멘트 조회 dto랑 같은데, 혹시 이 부분 마음에 걸리면 리뷰로 남겨주세요.
- 스웨거로 동작 테스트 확인 부탁드립니다.
- 추가로 리팩터링 원하시는 부분 있으면 리뷰 부탁드려요
> feat: 특정 카페 코멘트 중 나의 코멘트만 조회하는 api 구현

- src/main/java/mocacong/server/exception/badrequest/DuplicateNicknameException.java
- src/main/java/mocacong/server/repository/MemberRepository.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 중복된 이메일은 서버 쪽에서 막고 있었지만, 중복된 닉네임 가입은 막지 않고 있었습니다.
- 프론트 쪽에서 중복닉네임 시 post 요청을 못보내도록 해주고는 있었지만, 서버 쪽에서도 막는 게 필요해보였습니다.
- 이메일 뿐 아니라 닉네임이 중복되면 가입하지 못하도록 변경했습니다.
- api 변경은 없으므로 acceptanceTest, controller 변경은 없었습니다.
- DB I/O 비용을 줄이도록 `findByEmail`, `findByNickname` 두 개의 메서드 호출이 아닌 `findByEmailOrNickname` 메서드를 생성했습니다.
- 스웨거로 동작 테스트 부탁드립니다.
> fix: 이메일 뿐 아니라 닉네임이 중복되면 가입하지 못하도록 변경

- src/main/java/mocacong/server/controller/AuthController.java
- src/main/java/mocacong/server/dto/request/KakaoLoginRequest.java
- src/main/java/mocacong/server/dto/response/OAuthTokenResponse.java
- src/main/java/mocacong/server/security/auth/OAuthPlatformMemberResponse.java
- src/main/java/mocacong/server/security/auth/apple/AppleOAuthUserProvider.java
- src/main/java/mocacong/server/security/auth/kakao/KakaoAccessToken.java
- src/main/java/mocacong/server/security/auth/kakao/KakaoAccessTokenClient.java
- src/main/java/mocacong/server/security/auth/kakao/KakaoAccessTokenRequest.java
- src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
- src/main/java/mocacong/server/security/auth/kakao/KakaoUser.java
- src/main/java/mocacong/server/security/auth/kakao/KakaoUserClient.java
- src/main/java/mocacong/server/security/auth/kakao/KakaoUserRequest.java
- src/main/java/mocacong/server/service/AuthService.java
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/test/java/mocacong/server/acceptance/AuthAcceptanceTest.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/security/auth/apple/AppleOAuthUserProviderTest.java
- src/test/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProviderTest.java
- src/test/java/mocacong/server/service/AuthServiceTest.java
- src/test/resources/application.yml
- 카카오 oauth 로그인 api 구현
- feign client를 이용하여 카카오 oauth 로그인 api를 구현했습니다.
- apple feign 때와 달리 authorization code 등의 실제 환경변수 값을 요청으로 feign 통신하는 과정이 포함돼있어 feignClient 테스트 코드를 직접적으로 만들지 않았습니다.
- Service Server (백엔드)에서 하도록 안내돼있는 Step2, Step3 기능을 구현했습니다. 
-  카카오 서버와의 feign 통신이 잘 이루어지는지 확인해주세요. `@SpringQueryMap`을 도입해봤는데 올바르게 작동할지 모르겠네요.
- 이 테스트가 진행되려면 프론트 측에서 인가 코드 받는 기능이 구현이 되어있어야 합니다. 
- 추가하고 싶은 테스트 코드가 있으면 리뷰 남겨주세요.
- 동작하지 않는 부분이 있는지 확인해주세요.
- 카카오 OAuth에서는 OIDC 사용 활성화하는 경우 외에는 공개키 캐싱을 할 필요가 없어보이는데, 이 부분도 제가 잘못 알고 있을 수 있어서 한 번 확인해주시면 감사하겠습니다
> feat: kakao OAuth 로그인 api 구현

- src/main/java/mocacong/server/domain/Cafe.java
- src/test/java/mocacong/server/domain/CafeTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 이전에는 `both` 요청이 존재하지 않는다고 판단하여 `both`에 대한 처리를 진행하지 않았습니다. 
- 카페 리뷰 작성 시 스터디타입을 `both`로 작성할 경우 `solo`, `group` 모두에 투표한 것으로 간주하도록 도메인 로직을 수정했습니다.
- 리뷰 작성 요청으로 `both`가 주어지는 테스트가 존재하도록 일부 테스트를 수정했습니다.
- 도메인 로직이 올바른지만 확인해주시면 될 것 같습니다.
> fix: 카페 리뷰 작성 시 스터디타입에 `both` 선택이 가능하도록 로직 수정

- src/main/java/mocacong/server/dto/response/CommentResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/CommentService.java
- 프론트의 요청으로 기존 카페 코멘트를 조회할 때 response에 코멘트의 id 또한 같이 넘기도록 수정했습니다.
- `CommentResponse` 수정
- 카페 코멘트 조회 시, id 또한 같이 조회하도록 로직 수정
- 변경된 api 명세서가 올바른지 확인해주세요
> feat: 카페 코멘트 조회 시 코멘트 id 또한 조회하도록 로직 수정

- src/main/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProvider.java
- src/main/java/mocacong/server/service/AuthService.java
- src/test/java/mocacong/server/security/auth/kakao/KakaoOAuthUserProviderTest.java
- KAKAO OAuth 로그인하면 Platform이 KAKAO가 아닌 APPLE로 저장되는 버그 존재
- 카카오 인가코드가 잘못될 경우 400 Bad Request임에도 불구하고 500으로 처리되어 슬랙 알림 전송
- 플랫폼 저장이 각 OAuth 구현체에 따라 다르게 저장되도록 수정
- 잘못된 인가코드로 인해 Feign Exception 발생 시 예외 핸들링 구현
- 예외 핸들링이 마음에 드는지 확인해주세요.
- KAKAO OAuth 로그인하면 Platform이 KAKAO로 저장되는지는 프론트와 테스트해봐야될 것 같습니다. 이 부분은 일단 코드상으로만 확인해주세요.
> fix: KAKAO OAuth 플랫폼이 잘못 저장되는 버그 및 인가코드 예외 핸들링 구현

- src/main/java/mocacong/server/domain/Cafe.java
- src/main/java/mocacong/server/domain/cafedetail/Desk.java
- src/main/java/mocacong/server/domain/cafedetail/Parking.java
- src/main/java/mocacong/server/domain/cafedetail/Power.java
- src/main/java/mocacong/server/domain/cafedetail/Sound.java
- src/main/java/mocacong/server/domain/cafedetail/Toilet.java
- src/main/java/mocacong/server/domain/cafedetail/Wifi.java
- src/test/java/mocacong/server/domain/CafeTest.java
- 기존에는 최대값에 해당되는 객체 반환이었어서 아래와 같은 상황이 연출됩니다.
-  하나가 good(wifi 빵빵해요) 하나가 bad(wifi 느려요)이어도 soso(wifi 적당해요)가 아니라 둘 중 하나만 나옵니다.
- 카페 세부정보 계산하는 로직을 최대값에 해당되는 객체 반환에서 점수제(반올림)로 변경했습니다.
- 더 좋은 도메인 로직이 있다면 리뷰 부탁드립니다.
- null 관련하여 누락된 처리가 있는지 확인해주세요
> fix: 카페 세부정보 계산 로직 최대값에서 평균점수로 변경

- src/main/java/mocacong/server/controller/CommentController.java
- src/main/java/mocacong/server/exception/badrequest/InvalidCommentDeleteException.java
- src/main/java/mocacong/server/service/CommentService.java
- src/test/java/mocacong/server/acceptance/AcceptanceFixtures.java
- src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- 카페 코멘트 삭제 DELETE API를 구현했습니다.
- 카페 코멘트 삭제 DELETE API 구현
- 카페 코멘트 삭제 테스트 코드 작성
- api 스펙과 동일한지 확인해주세요
- 누락된 테스트가 있는지 확인해주세요
> feat: 카페 코멘트 삭제 DELETE API 구현

- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
- src/main/java/mocacong/server/dto/response/MyCommentCafesResponse.java
- src/main/java/mocacong/server/repository/CommentRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 마이페이지에서 자신이 작성한 코멘트 목록을 조회하는 API를 구현했습니다.
- 작성 코멘트 목록 조회 GET API 구현
- 작성 코멘트 목록 조회 테스트 코드 작성
- api spec과 동일하게 구현되었는지 확인해주세요
- 누락된 테스트가 있는지 확인해주세요
> feat: 작성 코멘트 목록 조회 GET API 구현

- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
- src/main/java/mocacong/server/dto/response/MyReviewCafesResponse.java
- src/main/java/mocacong/server/repository/CafeRepository.java
- src/main/java/mocacong/server/repository/ScoreRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/repository/CafeRepositoryTest.java
- src/test/java/mocacong/server/repository/ScoreRepositoryTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 자신이 리뷰를 남긴 카페 목록을 조회하는 API를 구현했습니다.
- 리뷰 남긴 카페 목록 조회 GET API 구현
- 리뷰 남긴 카페 목록 조회 테스트 코드 작성
- API 스펙과 동일하게 구현되었는지 확인해주세요
- 누락된 테스트 코드가 있는지 확인해주세요
> feat: 리뷰 남긴 카페 목록 조회 GET API 구현

- src/main/java/mocacong/server/controller/ControllerAdvice.java
- src/main/java/mocacong/server/support/SlackAlarmGenerator.java
- 에러 발생 시 슬랙 알람이 비동기가 아닌 동기로 작동하여 발생하고 있었습니다.
- 여러 사용자가 에러를 동시다발적으로 겪을 때 슬랙 알람 작업으로 인해 서버가 다운될 수 있습니다. 
- 슬랙 알람을 비동기로 구현했습니다. `@Async`는 AOP여서 private method에 작성하지 못하므로 슬랙 알람 클래스를 별도 분리했습니다. 오히려 책임 분리를 통해 코드가 깔끔해진 듯하네요.
- 에러 발생 시 슬랙에 알림이 잘 가는지 테스트해주세요. (실제 슬랙 채널에 테스트보내도 괜찮습니다.)
> feat: 에러 발생 시 슬랙 알람을 비동기로 보내도록 구현

- src/main/resources/application-dev.yml
- src/main/resources/logback-spring.xml
- 기존에는 운영 서버가 개발 서버 역할을 했습니다.
- 테스트를 실제 운영되고 있는 서버에 직접 해야 했습니다. 따라서 불필요한 알림이 전송됐었고, 서버 트래픽도 테스트와 실제 환경이 같이 감당했어야 했습니다.
- 개발 서버와 운영 서버를 분리했습니다. (subnet, ec2, rds, s3 버킷 생성)
- 아직 실제 앱 배포를 하지 않은 상태이기 때문에 CD(지속적 배포) 자동화 스크립트는 건드리지 않았습니다. 따라서 develop 브랜치에 머지가 되면 운영 서버도 develop 브랜치 코드를, 개발 서버는 수동으로 `run.sh`를 돌려야 develop 브랜치 코드를 가지게 했습니다. 단, DB는 개발 서버와 운영 서버가 분리돼있습니다. 따라서 데이터는 공유하지 않습니다. 
- 실제 앱 배포가 이루어지면 운영서버는 main 브랜치, 개발 서버는 develop 브랜치 코드를 가지도록 변경 필수
- 해당 PR이 머지가 되면 개발 DB에 더미 데이터를 많이 넣어둘 예정입니다. 
- aws 궁금한 세부적인 사항(가용 영역, IP 등)은 보안 관련 내용이므로 DM으로 부탁드립니다.
- 개발 서버는 별도의 도커 자동 배포를 설정하지 않았습니다. (docker hub private registry는 1개까지만 무료) 따라서 개발 서버 ec2에 기존처럼 `run.sh`를 만들어놓았습니다. 
- 하지만 **해당 PR이 머지되기 전에 `run.sh`를 실행하면 안됩니다**. 해당 PR 머지 전에는 스크립트 수행 시 `application-dev.yml` 이 없어서 `application.yml`이 수행될 것이며, …
> feat: 개발 서버와 운영 서버 분리

- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/dto/request/PasswordVerifyRequest.java
- src/main/java/mocacong/server/dto/response/PasswordVerifyResponse.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 회원정보를 수정하기 전 비밀번호 확인 인증을 하는 API를 구현했습니다.
- 비밀번호 확인 인증 API 구현
- 비밀번호 확인 인증 테스트 코드 작성
- api 스펙과 동일하게 구현되었는지 확인해주세요
> feat: 비밀번호 확인 인증 POST API 구현

- src/main/java/mocacong/server/config/AuthConfig.java
- src/main/java/mocacong/server/security/auth/LoginInterceptor.java
- 거의 30초~ 1분 간격으로 `LoginInterceptor.prehandle()`에서 에러가 발생하곤 했습니다.
이는 aws의 로드밸런서에서 health-check(사이트가 안정적인지 주기마다 로드밸런서에서 요청을 보내는 작업)를 위해 루트 디렉토리에 접근하기 때문입니다. (target group에서 health-check target을 `/swagger-ui/index.html`로 변경함에도 `/`로 로드밸런싱 후에 작업해서인지 계속 위 에러로그가 찍히네요)
그 외에 /index.html, 존재하지 않는 도메인 등에 접근할 때마다 해당 에러가 뜹니다.
30초~1분마다 로그인이 필요한 서비스도 아님에도 불구하고 이러한 에러가 뜰 필요가 없다고 생각했습니다.
- 우리 서비스에서 로그인 인증이 요구되는 도메인은 모두 `/members` 또는 `/cafes`로 시작합니다. 따라서 모든 path를 addPatterns 하는 방식에서 `/members/**` 또는 `/cafes/**`를 include하고 필요한 path만 제외하는 방식으로 변경했습니다.
- 이렇게 변경함으로써 로그인해야되는 path가 아님에도 불구하고 에러가 뜨는 현상 및 health-check 에러로그가 사라졌습니다.
- 보안적으로 이슈가 될만한 부분이 있는지 확인해주세요. 아무것도 없는 도메인에 접속한다 하더라도, 사실상 유저 입장에서 할 수 있는 건 없다고 생각돼서 보안 이슈가 없지 않을까 생각했습니다.
> feat: LoginInterceptor 적용 경로 변경

- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/dto/request/EmailVerifyCodeRequest.java
- src/main/java/mocacong/server/dto/response/EmailVerifyCodeResponse.java
- src/main/java/mocacong/server/exception/badrequest/InvalidNonceException.java
- src/main/java/mocacong/server/service/MemberService.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- src/test/resources/application.yml
- 기존에는 이메일 인증 시에 별도의 검증을 거치지 않았습니다. 하지만, 비밀번호 수정 프로세스 로직에 이메일 인증코드 인증 요청이 추가될 경우, 별도 검증을 하지 않으면 보안적 위험이 있게 됩니다.
- 이메일 인증이 postman 등의 유효하지 않은 요청에는 진행되지 않아야 합니다. 따라서 모카콩 클라이언트의 올바른 요청인지 검증을 위해 nonce 값 검증을 추가했습니다.
- 비밀번호 찾기 작업은 이메일(아이디)는 알고 있는 상태로 진행이 됩니다. 따라서 가입되지 않은 이메일로 인증하는 케이스를 검증하고 예외처리했습니다.
- github secret 변수의 application-prod.yml 을 수정했습니다. 해당 pr이 머지될 때 개발 서버 yml 환경변수 주입도 진행하겠습니다.
- 서비스 로직이 올바른지 확인해주세요.
- 누락된 테스트가 있는지 확인해주세요.
> feat: 이메일 인증 api 내 검증 로직 추가 구현

- src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
- src/main/java/mocacong/server/dto/response/MyFavoriteCafeResponse.java
- src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- 마이페이지에서 자신이 참여(리뷰, 댓글, 즐겨찾기)한 카페를 클릭 시에 해당 카페로 이동돼야 합니다. 그러기 위해선 해당 카페의 식별자가 필요합니다. 프론트 입장에서의 카페 식별자는 `mapId`입니다.
- 응답 API response에 `mapId`를 추가했습니다. 
- 비즈니스 로직이 변경된 부분이 없어서 테스트 코드의 수정 및 추가는 존재하지 않습니다.
- 제대로 변경됐는지 확인해주세요.
> fix: 마이페이지 참여 카페 반환 시 `mapId` 필드 추가하도록 수정

- src/main/java/mocacong/server/dto/response/CafeImagesResponse.java
- src/main/java/mocacong/server/dto/response/CommentsResponse.java
- src/main/java/mocacong/server/dto/response/MyCommentCafesResponse.java
- src/main/java/mocacong/server/dto/response/MyFavoriteCafesResponse.java
- src/main/java/mocacong/server/dto/response/MyReviewCafesResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/CommentService.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- 무한 스크롤 방식일 경우, 현재 페이지를 알 필요가 없고 더 이상 내릴 페이지가 있는지의 여부가 중요합니다.
- 페이지네이션이 요구되는 API 응답 필드를 `currentPage`에서 `isEnd`로 변경했습니다.
- 미처 변경하지 못한 부분이거나 놓친 부분이 있다면 리뷰 부탁드려요.
- 의도대로 동작되지 않는 부분이 있다면 리뷰 주세요.
> fix: 페이지네이션 API 응답 필드 `currentPage` -> `isEnd`로 변경

- src/main/java/mocacong/server/controller/ControllerAdvice.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/support/AwsS3Uploader.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/resources/application.yml
- 카페 이미지 저장/수정 그리고 회원 프로필 이미지를 수정할 때 따로 10MB 이상의 대용량 크기의 이미지 제한 예외가 따로 없었기에 추가하였습니다.
- application.yml 에 `resolve-lazily` , `max-swallow-size` 설정 추가
- `ExceptionHandler`에 `MaxUploadSizeExceededException` 핸들러 추가
- 스웨거를 통해 해당 예외가 반환되는 지 확인해주세요
- 로직이 제대로 구현됐는지 확인해주세요
- 해당 기능은 MockMVC로 테스트를 못하기에 테스트 코드 작성을 생략했습니다
> feat: MaxUploadSizeExceededException 예외 처리 추가

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/dto/response/PreviewCafeResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 프론트의 요청으로 카페 평점, 스터디타입, 즐겨찾기 여부, 리뷰 개수를 보여주는 카페 미리보기 조회 기능을 구현했습니다.
- 카페 미리보기 조회 기능 구현
- 카페 미리보기 조회 테스트 코드 작성
- 카페 미리보기 조회 인수테스트 코드 작성
- api 스펙과 동일한지 확인해주세요
- 누락된 테스트가 있는지 확인해주세요
> feat: 카페 정보 미리보기 조회 GET API 구현

- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/dto/response/GetUpdateProfileInfoResponse.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 프론트의 요청으로 프로필 수정 페이지에서 `email`, `nickname`, `phone` 를 조회하는 API를 구현했습니다.
- 프로필 수정 페이지 조회 GET API 구현
- 프로필 수정 페이지 조회 테스트 코드 작성
> feat: 프로필 수정 페이지 조회 GET API 구현

- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/dto/request/ResetPasswordRequest.java
- src/main/java/mocacong/server/dto/response/EmailVerifyCodeResponse.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 프론트 측에서 비밀번호 변경 API를 별도로 만들고 싶어하며, memberId가 아닌 token으로 처리할 수 있는 방향을 원했습니다.
- 이메일 인증 응답으로 사용가능한 token을 발급해주도록 변경했습니다. 이메일 인증이 완료되면 그 이후 요청부터는 프론트 측에서 헤더에 해당 토큰을 붙여줍니다.
- 비밀번호 변경 API에서 `memberId`가 아닌 header에 토큰을 담아서 요청하는 것으로 요청자의 식별을 가능하게 변경했습니다.
- API 변경사항에 적합하게 변경했는지, 동작에 문제는 없는지 확인해주세요
> fix: 이메일 인증 및 비밀번호 변경 API 에서 token 필요하도록 변경

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/dto/request/CafeFilterStudyTypeRequest.java
- src/main/java/mocacong/server/dto/response/CafeFilterStudyTypeResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- `studyType` 별로 카페 필터링을 할 때 GET인 경우에는 json 에러가 발생하여POST 로 변경했습니다.
- `studyType` 별 카페 필터링 조회 POST API로 변경
- 변경 사항에 따라 해당 테스트 코드 수정
- 오타가 있는지 확인해주세요.
- api spec과 동일한지 확인해주세요
> fix: studyType별로 카페 필터링 조회 API - POST API로 수정

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/dto/request/CafeFilterFavoritesRequest.java
- src/main/java/mocacong/server/dto/response/CafeFilterFavoritesResponse.java
- src/main/java/mocacong/server/repository/CafeRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/CafeAcceptanceTest.java
- src/test/java/mocacong/server/repository/CafeRepositoryTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 즐겨찾기한 카페를 필터링하여 카페 목록을 조회하는 API를 구현했습니다.
- 즐겨찾기한 카페 필터링 조회 POST API 구현
- 즐겨찾기한 카페 필터링 조회 테스트코드 작성
- api spec에 맞게 구현되었는지 확인해주세요
- 더 나은 로직이 있다면 알려주세요
> feat: 즐겨찾기한 카페 필터링 조회 POST API 구현

- build.gradle
- src/main/java/mocacong/server/config/RedisCacheConfig.java
- src/main/java/mocacong/server/config/RedisConfig.java
- src/main/java/mocacong/server/security/auth/apple/AppleClient.java
- src/main/java/mocacong/server/service/AuthService.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/FavoriteService.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/java/mocacong/server/acceptance/AcceptanceTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/ServiceTest.java
- src/test/java/mocacong/server/support/DatabaseCleaner.java
- src/test/java/mocacong/server/support/TestRedisConfig.java
- src/test/resources/application.yml
- 수정이 잦지 않고, 조회가 빈번한 api나 작업들이 존재합니다. 해당 작업들 중, 비교적 오래 걸리는 작업은 캐시를 적용할 필요성이 있어보였습니다.
- 카페 미리보기 API, Apple OAuth 공개키, accessToken 조회 시에 캐싱을 적용했습니다.
- 로컬에서 `redis-cli` 를 이용하여 조회하는 것을 추천드립니다. `redis`, `redis-cli`가 설치돼있지 않으면 카페 미리보기 조회 API가 실패합니다.
- **로컬에서는 elasticache 사용 불가능!** 본인 IP (`127.0.0.1`이 엔드포인트가 될 것입니다.)
- redis에 먼저 조회 -> 캐시가 있으면 해당 값을,  존재하지 않으면 실제로 DB 조회
- 개발 환경, 운영 환경은 비용 문제로 인해 동일한 elasticache를 참조합니다.
- `redis-cli -h {AWS Elasticache 엔드포인트} -p ${AWS Elasticache 포트}`
- 엔드포인트, 포트는 aws Elasticache의 Redis 클러스터에서 조회 가능합니다.
- 캐시 만료일자가 적절한지 체크해주세요.
> feat: Elasticache for Redis를 도입하여 캐싱 적용

- src/main/java/mocacong/server/dto/response/CafeMyReviewResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/FavoriteServiceTest.java
- 프론트의 요청으로 내가 작성하지 않은 특정 카페 리뷰에 대해 조회 할 때, 예외 대신 null을 보내주도록 변경했습니다
- 리뷰를 작성하지 않은 카페에 대해 내가 작성한 카페 리뷰 조회를 하는 경우 response에 null을 반환하도록 API 수정
- 해당 변경사항에 대해 테스트 코드 추가
- 더 좋은 로직이 있다면 추천해주세요
> fix: 내가 작성한 특정 카페 리뷰 조회 GET API 수정

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/exception/badrequest/ExceedCafeImagesCountsException.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 한 요청 당 이미지를 여러 개 올릴 수 있도록 변경 수요가 존재합니다.
- 카페 이미지를 요청 당 3개까지 올릴 수 있도록 구현했습니다.
- aws측에서 `putObjects` 벌크 연산을 지원하지 않습니다. (파일마다 메타데이터가 다르기 때문인 것으로 추측 중)
- for문으로 처리하였습니다.
- swagger로 동작 확인 부탁드려요
> feat: 카페 이미지를 요청 당 3개까지 올릴 수 있도록 구현

- src/main/java/mocacong/server/config/RedisCacheConfig.java
- src/main/java/mocacong/server/service/AuthService.java
- 자체 로그인 이후 캐시데이터가 생성되면, 이메일만 올바르고 비밀번호가 올바르지 않은 요청이 들어와도 토큰이 주어집니다.
- email을 key 값으로 캐시를 생성했기 때문입니다. 
- 자체 로그인 시 캐시를 제거했습니다.
- password 정보를 key 값에 포함하여 캐시를 유지하는 방법도 존재하지만, raw password가 남겨질 경우 법적으로도 문제가 될 수 있습니다.
- 또한, 이후에 refresh token 기능이 구현된다면 해당 토큰을 캐싱하면 되므로, 자체 로그인 access token은 제거하는 방안을 택했습니다.
- 모카콩의 현재 유저 수가 많지 않다는 점을 고려하면 캐시를 제거하는 것이 오히려 나을 수도 있겠다고 판단했습니다.
- 로컬에서 로그인했을 때 캐시가 생성되지 않는지 확인해주세요
- 심각한 버그이지만, 빠르게 머지할 필요는 없을 듯합니다. (배포 전이기 때문)
> fix: 자체 로그인 캐싱 제거

- .github/workflows/cd-backend.yml
- 메인 브랜치 최종 배포를 진행해야 합니다. 배포 이후에는, 개발 서버(베타 서버)에 머지되는 내용들이 실제 운영서버에 바로 머지되면 안됩니다.
ex) 개발 서버에서 리프레시 토큰 기능 도입, 유저 안정성 목적 등으로 인해 아직 운영서버에는 도입 안할 예정인 경우 
=> 개발서버(develop 브랜치)에만 머지되고, 운영서버(main 브랜치)에는 머지되면 안됨.
- 도커 자동 배포화 작업을 메인에서만 동작하도록 변경했습니다.
- 도커 외에 develop 브랜치에서 수행되지 않도록 변경돼야 하는 것이 있는데 놓친 것이 있으면 리뷰해주세요
- 개발 서버와 운영 서버가 현재 다른점
- ddl-auto
- develop: update
- main: validate
- docker CD
- develop: (이 PR이 머지되면) 미포함
- main: 포함
> feat: 운영 서버 배포를 위한 develop 브랜치 트리거 삭제

- src/main/java/mocacong/server/domain/Score.java
- src/main/java/mocacong/server/dto/response/CafeReviewUpdateResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 카페 세부정보를 수정할 때 null로 수정하면 NPE가 발생합니다.
- 세부정보 수정 후 결과 반환 시 Null을 허용하여 반환할 수 있도록 변경했습니다.
아래 형식대로 수정이 잘 되는지 확인 후, 조회까지 체크해주세요
```coffeescript
{
"myScore": 4,
"myStudyType": "group",
"myWifi": null,
"myParking": null,
"myToilet": null,
"myPower": null,
"mySound": null,
"myDesk": null
}
```
> fix: 카페 세부정보 수정 후 결과 반환 시 null 허용

- src/main/java/mocacong/server/support/logging/LoggingAspect.java
- 기존 로그에는 request 메서드, request Body, response time, exception 정도를 알 수 있었습니다. 
- 하지만, **응답값이 무엇인지는 알기 어렵습니다.** 아래 사진은 오늘 QA를 진행하면서 발생한 로그입니다.
response body가 무엇인지 알기 어렵습니다.
- response body가 로그에 남도록 Spring AOP의 `@AfterReturning`으로 구현했습니다. 예외 발생 시 트리거가 발생하는 `@AfterThrowing`는 진행하지 않았습니다. 현재 로그 정책으로도 에러 원인 파악은 무난하다고 생각했기 때문이에요.
```coffeescript
[2023-06-07 23:48:50:254514] [http-nio-8080-exec-2] INFO  [mocacong.server.support.logging.LoggingAspect.allControllerResponse:77] - method: findComments, result: <200 OK OK,CommentsResponse(isEnd=true, comments=[CommentResponse(id=1, imgUrl=null, nickname=케이, content=혼코딩하기 좋고, 그리고 개인적으론 음료도 나쁘지 않았어요, isMe=true)]),[]>
[2023-06-07 23:48:50:254516] [http-nio-8080-exec-2] INFO  [mocacong.server.support.logging.LoggingTracer.end:33] - [b7734bea] <--- …
```
> feat: 응답값을 로그에 남기도록 구현

- src/main/java/mocacong/server/domain/Member.java
- src/main/java/mocacong/server/repository/MemberRepository.java
- src/main/java/mocacong/server/service/AuthService.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/service/AuthServiceTest.java
- 기존 회원가입 로직에서는 회원 중복 체크를 할 때 이메일로만 검증했으므로 OAuth 이메일과 동일한 이메일로 회원가입을 진행할 시 `DuplicateMemberException`이 터졌습니다. 이를 방지하기 위해 uniqueConstraints를 적용해 회원가입 시, `email` 과 `platform` 이 함께 일치하는 경우에만 `DuplicateMemberException`를 던지도록 변경했습니다.
- Member 엔티티에 uniqueConstraints 추가
- 회원 중복 체크 로직 수정
- 회원가입을 진행한 이메일로 OAuth 로그인을 시도할 때 정상적으로 작동하는 지 검증하는 테스트 코드 추가
- 회원 중복 체크 로직이 올바른지 확인해주세요
- Kakao OAuth 로그인으로 uniqueConstraints가 적용되었음을 확인했습니다
- 추가된 테스트 코드가 올바른지 확인해주세요
> fix: 이메일과 플랫폼 일치 여부를 확인하는 회원 중복 체크로 변경

- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 회원 탈퇴 시에, 해당 회원의 프로필 이미지 또한 삭제시켜주어야 합니다.
- 회원탈퇴가 발생하면 해당 프로필 이미지의 `isUsed`를 false로 변경시키는 기능을 추가했습니다.
- 해당 이미지는 새벽 4시에 스케줄러로 인해 삭제됩니다.
- 다시 재가입한다 하더라도, 해당 이미지가 보여지지 않습니다. 
- 회원 탈퇴 시에 이미지의 `isUsed` 값이 `false`로 바뀌는지 확인해주세요.
- 회원 탈퇴 후 재가입 시, 프로필 이미지가 null 로 설정되는지 확인해주세요.
- 개발용 S3 로 테스트 후에, 테스트한 이미지는 S3 버킷에 접속 후 지워주세요.
> feat: 회원 탈퇴 시, 프로필 이미지 연동 해제 기능 구현

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/controller/CommentController.java
- src/main/java/mocacong/server/domain/Comment.java
- src/main/java/mocacong/server/dto/request/CafeReviewRequest.java
- src/main/java/mocacong/server/dto/request/CafeReviewUpdateRequest.java
- DTO 단에서 공백 예외처리 등 일부 예외처리를 진행하고 있지 않은 케이스가 있었습니다.
- 누락된 `@Valid`를 추가했습니다.
- 필터링 관련 API는 `@Valid`를 사용하는 DTO가 없어서 `@Valid`를 추가하지 않았습니다. 그 외 API의 requestbody에는 모두 붙여주었습니다.
- 리뷰 작성 및 수정, 코멘트 작성 및 수정 시에 모카콩 프로세스 로직대로 예외 핸들링 잘 되는지 확인해주세요.
- 누락된 `@Valid`가 있는지 확인해주세요.
> fix: 누락된 `@Valid` 추가

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 기존 studyType별 카페 필터링은 인자로 넘어온 studyType에 해당하는 카페들만 반환했습니다. 이제는 `solo` 나 `group` 카페를 필터링 할 때도 `both` 에 해당하는 카페도 함께 반환하도록 수정했습니다.
- studyType별 카페 필터링 로직 변경
- studyType별 카페 필터링 테스트 코드 변경
- swagger로 정상 동작되는지 확인 부탁해요
> fix: studyType별 카페 필터링 로직 both 함께 반환하도록 변경

- src/main/java/mocacong/server/domain/Cafe.java
- src/main/java/mocacong/server/dto/request/CafeReviewRequest.java
- src/main/java/mocacong/server/dto/request/CafeReviewUpdateRequest.java
- 리뷰 작성 시, 스터디타입과 평점은 필수로 입력해야 합니다. 따라서 스터디타입에 null을 허용하지 않도록 해야 합니다.
- 리뷰 작성 한정, 스터디타입에 `@NotBlank`를 추가했습니다.
- 카페 자체의 studyType은 Null이 될 수 있으므로 column 자체에 `nullable=false`는 걸지 않았습니다.
- 카페 세부정보 갱신 로직을 엄밀하게 변경했습니다.
- 리뷰에 null이 들어오는 경우의 검증은 DTO 단에서 해주므로 테스트 코드의 변경은 하지 않았습니다.  
- Swagger로 리뷰 스터디타입 이것저것 넣어서 테스트 부탁드려요
> fix: 나의 스터디타입 필드 null 불가능하도록 변경

- src/main/java/mocacong/server/service/CafeService.java
- 리뷰 수정으로 인한 평점이 수정됨에도 불구하고, 카페 미리보기 API와 카페 조회 API에서 반환하는 평점이 다릅니다.
- 리뷰 수정 시 카페 미리보기 API 의 캐시를 무효화하도록 하였습니다.
- Swagger로 아래 카페 리뷰 등록 후, 평점 수정 시에 미리보기 API, 조회 API가 서로 같은 평점을 반환하는지 확인해주세요.
> feat: 리뷰 수정 시 카페 미리보기 캐시 무효화

- src/main/java/mocacong/server/repository/CafeImageRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/repository/CafeImageRepositoryTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 기존 카페 이미지 조회 기능에서는 카페 이미지들을 카페 이미지 id 기준 오름차순으로 정렬하여 반환했습니다. 하지만 프론트의 요청으로 카페 이미지를 조회할 시, 먼저 자신이 올린 이미지를 최근 순으로 정렬하고 타인이 올린 이미지를 최근 순으로 정렬하여 반환하도록 수정했습니다.
- 카페 이미지 조회 로직을 자신이 올린 사진부터 최근 순으로 정렬하도록 수정
- 카페 이미지 조회할 시, 최근 순으로 정렬이 되는지 검증하는 테스트 코드 추가
- 카페 이미지 조회 로직 수정에 따른 기존 카페 이미지 관련 테스트 코드 수정
- 스웨거로 `특정 카페 조회`, `카페 이미지 조회` 두가지 기능이 정상적으로 동작되는지 확인해주세요
- 더 나은 로직이 있다면 추천해주세요
> fix: 카페 이미지 조회 GET API 로직 최근 순으로 정렬하도록 수정

- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/domain/CafeImage.java
- src/main/java/mocacong/server/repository/CafeImageRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/CommentService.java
- src/main/java/mocacong/server/service/FavoriteService.java
- src/main/java/mocacong/server/service/MemberService.java
- src/main/java/mocacong/server/service/event/DeleteMemberEvent.java
- src/test/java/mocacong/server/domain/CafeImageTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 카페 이미지가 등록된 회원이 탈퇴하려 하면, 외래키 제약조건으로 인해 탈퇴가 불가능합니다. 
- #44 PR과 마찬가지로 이벤트리스너로 프로필 이미지 작성자를 null 처리한 후에 회원탈퇴가 되도록 하였습니다.
- 탈퇴한 회원의 카페 이미지가 포함된, 카페 정보 조회 시에 문제가 없도록 카페이미지 엔티티 로직 null 처리로직을 변경했습니다.
- 회원탈퇴가 올바르게 되는지, 그 이후에 다른 회원이 카페 이미지를 조회할 때 문제가 없는지 확인해주세요.
> fix: 카페 이미지 등록 시 회원탈퇴가 불가능한 버그 수정

- src/main/java/mocacong/server/controller/ControllerAdvice.java
- src/main/java/mocacong/server/exception/badrequest/InvalidFileEmptyException.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/support/AwsS3Uploader.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 손상된 파일로 요청이 오는 경우 500번대 에러가 발생합니다.
```java
nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.impl.IOFileUploadException: 
Processing of multipart/form-data request failed. java.io.EOFException
```
- 카페 이미지를 수정할 때, 없는 파일은 업로드할 수 없습니다. 하지만 파일 자체는 존재하나 사이즈가 0인 경우는 그대로 업로드됩니다.
- 손상된 파일 요청을 9006번 예외 발생하도록 핸들링했습니다.
- 빈 파일 체크 여부를 CafeService, MemberService 에서 AwsS3Uploader 객체에게 위임했습니다.
- 카페 이미지 여러 개 업로드 시, 2개 빈 파일이고 1개 정상적 이미지 파일일 경우  1개만 잘 올라가는 것을 확인했습니다.
- 사이즈가 0인 빈 파일 업로드 시 9007번 예외 발생하도록 핸들링했습니다. 
- **9007번 예외 발생 프로세스 로직은 프론트 측과 최종 협의가 되지 않았습니다. 프론트가 동의하면 그대로 유지, 동의하지 않으면 `e6845a2 (feat: 빈 파일 업로드 시 예외 발생 구현)` 커밋은 롤백 예정입니다.**
- 회원 프로필 이미지 등록, 수정, 카페 이미지 업로드, 여러 개 업로드, 수정 기능이 잘 동작하는지 확인해주세요.
- 빈 파일 업로드 시 예외를 발생시키는지 확인해주세요.
- 카페 이미지 여러 개 업로드 시, 하나라도 비어있는 파일이 아닐 …
> feat: 파일 손상 및 요청 에러 예외 핸들링

- src/main/java/mocacong/server/repository/CafeImageRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/repository/CafeImageRepositoryTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 프론트의 요청으로 카페 이미지를 최신순(DESC) 정렬에서 등록순(ASC) 정렬로 수정하였습니다.
- 정렬 Repository 메서드 쿼리문 수정
- 정렬 수정으로 인한 테스트 코드 수정
- 프론트의 요청사항에 맞게 수정되었는지 포스트맨이나 스웨거로 확인해주세요
- 추가적으로 필요한 테스트 코드가 있는지 확인해주세요
> fix: 카페 이미지 조회 정렬 로직 ASC로 수정

- src/main/java/mocacong/server/domain/Cafe.java
- src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
- src/main/java/mocacong/server/dto/response/MyFavoriteCafeResponse.java
- src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/domain/CafeTest.java
- 마이페이지에서 카페 조회 시, 스터디 타입까지 반환해달라는 기획 요청 존재
- 마이페이지에서 즐겨찾기 목록 조회, 리뷰 남긴 카페 목록 조회, 코멘트 목록 조회 시에 API를 수정했습니다.
- 해당 카페의 studyType이 같이 뜨도록 변경
- 리뷰가 하나도 없는 카페의 studyType 조회 시에 에러가 뜨지 않고 null이 안전하게 뜨도록 구현했습니다.
- 해당 도메인 메서드의 테스트 코드를 작성했으며, 단순 DTO 변경 부분은 테스트 코드 미작성했습니다. 
- NPE나 에러가 날만한 부분이 있는지 확인해주세요
> feat: 마이페이지 카페 조회 시, 스터디타입을 함께 반환하도록 구현

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/controller/CommentController.java
- src/main/java/mocacong/server/controller/FavoriteController.java
- src/main/java/mocacong/server/controller/MemberController.java
- src/main/java/mocacong/server/domain/Member.java
- src/main/java/mocacong/server/repository/CafeRepository.java
- src/main/java/mocacong/server/repository/MemberRepository.java
- src/main/java/mocacong/server/security/auth/AuthenticationPrincipalArgumentResolver.java
- src/main/java/mocacong/server/security/auth/JwtTokenProvider.java
- src/main/java/mocacong/server/security/auth/LoginUserId.java
- src/main/java/mocacong/server/service/AuthService.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/CommentService.java
- src/main/java/mocacong/server/service/FavoriteService.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/repository/CafeRepositoryTest.java
- src/test/java/mocacong/server/security/auth/JwtTokenProviderTest.java
- src/test/java/mocacong/server/service/CafeConcurrentServiceTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- src/test/java/mocacong/server/service/FavoriteConcurrentServiceTest.java
- src/test/java/mocacong/server/service/FavoriteServiceTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- 기존 로직에서는 회원 체크를 할 때 findByEmail을 이용해서 했기 때문에 Platform 상관없이 `email`이 같으면 중복된 회원으로 인식했습니다. 이 문제를 해결하고자 회원 체크를 `email` 과 `Platform` 두가지를 이용해 확인하거나 `memberRepository`의 `findById` 를 통해 확인하도록 로직을 변경했습니다.
- token payload를 `email` 에서 `memberId` 로 변경
- 그에 따라 코드 내에서  `findByEmail` 대신 `findById` 를 사용하도록 코드를 변경했습니다
- `@LoginUserEmail` 에서 `@LoginUserId` 로 이름 변경했습니다
- `memberRepository`에서 `findByEmail` 메서드를 삭제했습니다
- `validateDuplicateMember` 와 `isDuplicateEmail` 메서드 로직에서 `email` 과 `Platform` 모두 체크하도록 변경
- 해당 변경 사항에 따른 테스트 코드 수정
- 놓친 수정 사항이 있는지 확인해주세요
- 테스트 코드 파일 변경사항은 `member.getEmail()`에서 `member.getId()` 로 변경한 것 뿐이므로 테스트 코드 파일 외의 파일들을 집중적으로 확인해주시면 됩니다
> fix: 회원가입 시 이메일 확인 로직과 이메일 중복체크 로직 동일

- src/main/java/mocacong/server/domain/CafeImage.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/domain/CafeImageTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 기존 로직에서는 카페 이미지 수정 시, id를 새로 반환해주었습니다. 프론트 측에서 매번 GET으로 새 id를 조회해야 합니다. (프론트 측에서는 카페 이미지 수정 로직에서 캐싱된 값을 꺼내는 듯함.)
- 카페 이미지 변경 로직을 변경했습니다.
- 기존
- 변경하는 이미지를 새로 save해주어 id가 바뀜. 그리고 변경 전 이미지의 `is_used`는 false로 설정해줬었음.
- 변경
- 변경하는 이미지 url을 얻어와서 imgUrl 값을 update. 변경 전 이미지는 `is_used` false인 상태로 새로 save (S3 배치 삭제 대상에 포함되도록) 
- swagger와 h2로 카페 이미지 변경 시 img_url 변경이 잘 되는지 여부, 기존 이미지가 `is_used=false`인 상태로 DB에 남아있는지 확인해주세요
> feat: 카페 이미지 url 수정 시 동일 id 반환하도록 로직 변경

- src/main/java/mocacong/server/dto/response/MyReviewCafeResponse.java
- src/main/java/mocacong/server/repository/CafeRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/repository/CafeRepositoryTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
원래 내가 리뷰를 작성한 카페 조회 시 내가 작성한 리뷰의 studyType이 아닌 카페의 studyType이 그대로 반환됨.
이를 **내가 작성한 리뷰의 studyType이 반환되게끔 변경**
1. 내가 리뷰를 작성한 카페를 DB에서 조회 (1번)
2. 카페 반복문을 돌며 DB에서 내가 작성한 리뷰의 score와 studyType 조회 (2N번)
결과적으로 쿼리가 2N+1번 나가던 상황.
Repository에서 **DTO 조회**를 통해 쿼리 한번으로 카페 mapId, 카페 mapId, name, score, studyType이 조회되게끔 수정. 
그 결과 member 조회 쿼리 1, dto 조회 쿼리 1 총 2번의 쿼리문으로 모든 기능 구현. 
특정 데이터만 db에서 조회하는 것이기 때문에 커버링 인덱스를 활용가능하다.
그러나 해당 마이페이지 카페 조회 api가 자주 불리는가, 해당 api가 좋은 성능을 요구하는가 등에 대한 파악이 아직 필요하여 **db 인덱스를 만들어주지 않았음**
dto를 repository layer에서 까지 알게하는 것은 api spec이 변경되었을 때 repository의 변경을 야기할 수 있다.
즉, 유연하지 않은 설계라고 볼 수 있는데 이를 위한 화면 최적화한 repository 와 service (e.g. queryService)로 분리하는 과정이 필요할 수 있다.
> feat: 내가 리뷰를 작성한 카페 조회 시 작성한 리뷰의 studyType이 반환되게끔 기능 수정

- src/main/java/mocacong/server/exception/badrequest/BlankTokenException.java
- src/main/java/mocacong/server/security/auth/AuthorizationExtractor.java
- src/test/java/mocacong/server/security/auth/AuthorizationExtractorTest.java
- 기존 `extractAccessToken` 는 `request` 로 들어온 토큰 값이 공백이 아닌지에 대한 검증 로직을 포함하지 않았습니다. `extractAccessToken` 로직에서 분할된 헤더 값이 두 개 이상(인증 유형 + 토큰)인지 확인하여 헤더 값이 하나인 경우(공백 토큰) `BlankTokenException` 예외를 반환하도록 했습니다.
- `BlankTokenException` 커스텀 예외 추가
- `extractAccessToken` 로직에서 공백 값에 대한 토큰 공백 커스텀 예외 처리 추가
- `BlankTokenException` 예외 반환 테스트 코드 추가
- 포스트맨으로 해당 예외가 잘 반환되는지 확인해주세요
- 더 좋은 로직이 있다면 추천해주세요
> feat: 공백 값에 대한 토큰 공백 커스텀 예외 처리 추가

- src/main/resources/logback-spring.xml
- 모카콩 로그에서 마스킹 (`***` 처리) 되는 컬럼에 이메일이 포함돼있습니다. 하지만 이메일이 마스킹처리되면 유저를 식별하기 어렵다는 점, 이메일 자체만으로 크래킹에 악용될 여지는 적다는 점이 존재합니다.
- 개발 환경, 운영 환경에서 이메일 마스킹 처리를 제외했습니다.
- logback 설정 관련해서 추가로 리뷰남기고 싶은 사항이 있으면 편하게 남겨주세요.
- 이메일 마스킹 처리가 필요하다 싶으면 리뷰남겨주세요. 확인 후에 pr merge 또는 closed 하겠습니다.
> feat: 로그 마스킹 처리에 이메일 제외

- src/main/java/mocacong/server/domain/Cafe.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- cafeImage가 비즈니스 로직에 따라 여러 조건이 붙어 더 이상 즉시 로딩으로 cafeImage를 가져올 필요가 없어졌습니다.
- 이에 따라 cafeImage를 지연로딩으로 변경하였습니다.
- cafe의 cafeImage 지연로딩으로 수정하였습니다.
- 이에 따라 변경이 필요해진 테스트 코드를 함께 수정하였습니다.
- 더 나은 로직 혹은 방법이 있다면 말씀해주세요.
> feat: cafeImage 즉시로딩에서 지연로딩으로 변경

- src/main/java/mocacong/server/dto/response/CommentsResponse.java
- src/main/java/mocacong/server/repository/CommentRepository.java
- src/main/java/mocacong/server/service/CommentService.java
- src/test/java/mocacong/server/acceptance/CommentAcceptanceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- 코멘트 첫페이지 조회 시 전체 코멘트 개수가 필요해짐에 따라 해당 기능을 구현했습니다.
- 페이지가 0일 때만 count 쿼리를 통해 전체 댓글 개수를 함께 반환하도록 하였습니다.
- 반환 json이 count가 필요한지 아닌지에 따라 동적으로 변할 필요가 있어 dto의 count 필드 값에 Null 값이 들어와있을 때 json으로 변환되지 않도록 로직을 만들었는데, 혹시 더 좋은 방법이 있다면 추천해주세요.
> feat: 코멘트 첫페이지 조회 시 전체 코멘트 개수 반환 기능 구현

- src/main/java/mocacong/server/controller/CommentLikeController.java
- src/main/java/mocacong/server/domain/CommentLike.java
- src/main/java/mocacong/server/dto/response/CommentLikeSaveResponse.java
- src/main/java/mocacong/server/exception/badrequest/AlreadyExistsCommentLike.java
- src/main/java/mocacong/server/exception/badrequest/InvalidCommentLikeException.java
- src/main/java/mocacong/server/exception/notfound/NotFoundCommentLikeException.java
- src/main/java/mocacong/server/repository/CommentLikeRepository.java
- src/main/java/mocacong/server/service/CommentLikeService.java
- src/main/java/mocacong/server/service/CommentService.java
- src/main/java/mocacong/server/service/event/DeleteCommentEvent.java
- src/test/java/mocacong/server/acceptance/CommentLikeAcceptanceTest.java
- src/test/java/mocacong/server/repository/CommentLikeRepositoryTest.java
- src/test/java/mocacong/server/repository/CommentRepositoryTest.java
- src/test/java/mocacong/server/service/CommentLikeConcurrentServiceTest.java
- src/test/java/mocacong/server/service/CommentLikeServiceTest.java
- src/test/java/mocacong/server/service/CommentServiceTest.java
- 댓글 좋아요 등록 기능이 추가되었습니다.
- 댓글 좋아요 취소 기능이 추가되었습니다.
- 댓글과 댓글에 좋아요한 유저의 정보를 담기위한 CommentLike 테이블을 새롭게 생성하였습니다.
- 한 유저가 한 댓글에 여러번 좋아요할 수 없도록 데이터베이스 unique 무결성 제약을 걸어 동시성을 고려하였습니다.
- 추가로 동시성 테스트도 구현하였습니다.
- 스웨거로 정상 동작하는지 확인하였습니다.
- 댓글 좋아요 취소 기능을 구현했습니다.
- 댓글 좋아요 취소 시 inner join과 id 값만을 받아와 커버링 인덱스를 타도록 구현했습니다.
- 유저가 삭제되었을 때 FK 무결성 제약조건을 해결하기 위해, EventListner를 이용해 유저가 삭제되었을 때 연결 관계를 끊어주었습니다.
- 유저가 삭제된다고 댓글 좋아요 기록은 사라지지 않기 때문에 이를 반영하여 CommentLike를 삭제하진 않았습니다.
- 댓글 좋아요에 cafes의 mapId가 필요없어 path가 바뀌게 되었는데, 혹시 더 좋은 방법이 있다면 말씀해주세요.
- 동시성 테스트에 더 좋은 방법이 있다면 추천해주세요.
> feat: 댓글 좋아요 등록 기능 구현

- src/main/java/mocacong/server/controller/CafeController.java
- src/main/java/mocacong/server/dto/response/CafeImageSaveResponse.java
- src/main/java/mocacong/server/dto/response/CafeImagesSaveResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- CafeImage 등록시 등록된 id를 반환하도록 구현하였습니다.
- 테스트 시 aws3 upload mocking이 필요하여 serviceTest에 테스트 작성하였습니다.
- 새로운 dto가 추가되었습니다.
- api spec이 변경되었습니다.
- 크게 로직은 없지만 더 좋은 변경 구조가 있다면 알려주세요.
> feat: CafeImage 등록시 등록된 id 함께 반환 구현

- src/main/java/mocacong/server/dto/request/CafeReviewRequest.java
- src/main/java/mocacong/server/dto/request/CafeReviewUpdateRequest.java
- 카페 리뷰 작성 및 수정 로직이 콘센트와 책상 필드 또한 필수로 입력하도록 수정되어 API를 수정했습니다.
- 카페 리뷰 작성 및 수정 response에서 콘센트, 책상 필드 @Notnull 옵션 추가
- 제대로 작동하는 지 포스트맨이나 스웨거로 확인해주세요
- `@NotNull` 을 requestBody 필드에 추가하였기 때문에 따로 해당 pr에 대한 테스트 코드를 작성하지 않았습니다.
> fix: 카페 세부정보 콘센트, 책상 필드 @NotNull 추가

- src/main/java/mocacong/server/dto/response/CafeImageSaveResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- 카페 이미지 등록 response에 카페 이미지 id 리스트와 userReportCount가 동시에 추가되면서 response가 아래 사진같이 반환되고 있었습니다. 앞으로 refresh Token을 추가할 예정이기에 카페 이미지 등록 response에서 userReportCount를 리스트 뒤에 나오도록 수정하는 것보다 삭제하는 게 맞다고 생각해 해당 필드를 제거했습니다. 
- CafeImageSaveResponse에서 userReportCount 제거
- 다른 좋은 생각이 있다면 코멘트 남겨주세요
- 해당 PR이 approve된다면 배포 1.0.1에 포함되도록 머지할 예정입니다
> fix: 카페 이미지 등록 response에서 userReportCount 제거

- src/main/java/mocacong/server/controller/ReportController.java
- src/main/java/mocacong/server/domain/CafeImage.java
- src/main/java/mocacong/server/domain/Comment.java
- src/main/java/mocacong/server/domain/Report.java
- src/main/java/mocacong/server/dto/request/CafeImageReportRequest.java
- src/main/java/mocacong/server/dto/response/CafeImageReportResponse.java
- src/main/java/mocacong/server/exception/badrequest/DuplicateReportCafeImageException.java
- src/main/java/mocacong/server/exception/badrequest/InvalidCafeImageReportException.java
- src/main/java/mocacong/server/repository/CafeImageRepository.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/ReportService.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/java/mocacong/server/service/ReportConcurrentServiceTest.java
- src/test/java/mocacong/server/service/ReportServiceTest.java
- 카페 이미지를 신고할 수 있는 카페 이미지 신고 기능을 추가했습니다.
- 카페 이미지 신고 기능 구현
- 카페 이미지에 신고 3회가 들어온 경우, 해당 카페 이미지 노출이 안되도록 마스킹 처리 및 작성자 경고 처리
- 기존 사용하지 않는 카페 이미지 삭제 배치 작업 로직을 `isUsed == false && isMasked == false`인 경우에만 동작하도록 수정
- 카페 이미지 신고 기능 관련 단위 테스트 및 동시성 테스트 코드 작성
- 인수테스트를 한다면 테스트 환경에 S3 설정을 넣어줘야 하기 때문에 이미지 관련 API에서는 인수 테스트를 생략했습니다.
- 스웨거 혹은 포스트맨으로 동작 확인해주세요
> feat: 카페 이미지 신고 기능 POST API 구현

- src/main/java/mocacong/server/domain/CafeImage.java
- src/main/java/mocacong/server/domain/Comment.java
- src/main/java/mocacong/server/domain/Member.java
- src/main/java/mocacong/server/service/ReportService.java
- src/test/java/mocacong/server/service/ReportServiceTest.java
- 댓글/카페 이미지가 마스킹 되어야 회원 경고가 1회씩 추가되던 기존 로직에서 댓글/카페 이미지에 신고가 들어올 때마다 회원 경고가 1회씩 추가되도록 수정했습니다
- 회원 경고 추가 기준 수정
- 회원 기간 정지 기준을 11회에서 5회로 수정
- 위의 변경사항에 따른 테스트 코드 수정
- 신고 로직 코드를 간결화할 좋은 방법이 있다면 알려주세요
> fix: 회원 경고 추가 기준 수정

- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- 현재 sql 로그가 `hibernate.show_sql = true` 로 인해 `System.out.print` 로 남아 느림. [참고](https://zzang9ha.tistory.com/399)
- 애플리케이션 메서드 관련 로그 외에 추가로 트랜잭션, 커넥션 관련 상황을 로그로 남기고 싶음.
- `hibernate.show_sql = false`
- 가독성을 위하여 `format_sql = true` 는 유지 
- `logback-spring.xml` 파일에 트랜잭션, 커넥션, SQL binding parameter 로거 추가
- System.out.print 이용한 SQL 로깅
- request DTO, response DTO 외에 DB에 저장되는 정보는 알 수 없음
- 애플리케이션 메서드 정보 외에는 알 수 없음.
- SqlStatementLogger를 이용한 로깅으로 인해 I/O 비용 감소
- request DTO, response DTO 외에 DB 저장 정보 알 수 있음.
- 유휴 커넥션 정보 알 수 있음. 데드락, Connection Timeout Error 방지에 용이하리라 기대됨.
- 트랜잭션 시작과 끝을 알 수 있음. 트랜잭션 관리 생산성 증가가 기대됨.
- 머지할 때 `application-prod.yml` 파일에서 `hibernate.show_sql = true`를 제거해주셔야 운영서버에도 적용이 됩니다.
- 마스킹 처리가 안되는 부분 있으면 리뷰 부탁드립니다. (마스킹 관련 이슈 있으면 binding-parameter logger는 제거할 수도 있습니다.)
> feat: 비효율적인 로그 제거 및 커넥션 관련 로깅 추가

- src/main/java/mocacong/server/domain/Comment.java
- src/main/java/mocacong/server/dto/response/CommentResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/main/java/mocacong/server/service/CommentService.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/java/mocacong/server/service/CafeServiceTest.java
- src/test/resources/application.yml
- 댓글 조회 시 commentLike의 수를 함께 조회하도록 구현했습니다.
- N+1 문제를 해결하기 위해 default_batch_fetch_size 옵션을 더해 1+1의 쿼리가 나가도록 했습니다.
- comment N개가 있어도 OneToMany관계의 CommentLike 쿼리가 1번만 나갑니다.
- application-prod.yml 도 바꿔야합니다. approve되면 merge하기 전에 바꾸겠습니다.
- 컬렉션 패치 조인 시 N+1 문제를 극복하는 더 좋은 방법이 있다면 말씀해주세요.
> feat: 댓글 조회 시 commentLike의 수 함께 조회하도록 구현

- src/main/java/mocacong/server/domain/Cafe.java
- src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/domain/CafeTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 현재 마이페이지에서 회원이 작성한 댓글 목록을 조회할 경우, 별다른 정렬 순서 없이 댓글 목록을 보여주고 있습니다.
- 이에 따라, 카페 별로 필터링하여 조회할 수 있도록 API Spec이 아래와 같이 댓글 목록을 list로 받도록 변경됐습니다.
- 필터링되도록 작업.
- TODO 에도 적어놨지만, 댓글 목록을 카페 별로 필터링하기 위해 DB에서 전체를 find하도록 작업했습니다. 
- 카페 종류 수에 따라 페이지네이션할지, 댓글 개수에 따라 페이지네이션할지 협의가 필요합니다. 
- 댓글 개수에 따라 페이지네이션한다면? 상위 DTO(`List<MyCommentCafeResponse`)의 사이즈는 고려하지 않고, 하위 DTO (`List<String> comments`)의 사이즈는 count 개수만큼이 되도록 해야 하는데, 이 역시 Slice로 하기 힘들어보였습니다. Slice로 할 경우 상위 DTO(`List<MyCommentCafeResponse`) 개수만큼 슬라이싱되기 때문.
- 따라서 우선은 카페 종류 수대로 페이지네이션했습니다. (카페 25군데, 댓글 80개 작성했을 경우 -> page(0, 5) 시에 카페 5군데에 작성한 댓글 전체를 보여줌.)
- 관련 스레드: https://mocacong.slack.com/archives/C04SGLLG2MC/p1699671506353769?thread_ts=1699615459.688409&cid=C04SGLLG2MC
- DB에서 native query로 new map으로 필터링처리를 하게 해버리게 쿼리를 짜보려 했는데, map은 중복 key 허용을 안해서 …
> feat: 마이페이지 회원 작성 댓글 목록 조회 시, 카페 별로 필터링되도록 구현

- src/main/java/mocacong/server/dto/response/MyCommentCafeResponse.java
- src/main/java/mocacong/server/service/CafeService.java
- src/test/java/mocacong/server/acceptance/MemberAcceptanceTest.java
- src/test/java/mocacong/server/service/CafeServiceTest.java
- 프론트의 요청으로 내가 남긴 댓글 조회 DTO의 comments 필드명을 commentContents로 수정했습니다.
- 내가 남긴 댓글 조회 DTO comments 필드명 수정
- 추가적으로 수정해야할 필드가 있는지 확인해주세요.
> fix: MyCommentCafeResponse에서의 comments 필드명 변경

- src/main/java/mocacong/server/exception/badrequest/ExceedCageImagesTotalCountsException.java
- src/main/java/mocacong/server/service/CafeService.java
- 한 카페에 대해 사용자가 4개 이상의 카페 이미지를 등록할 시, 예외를 반환해야 합니다. 기존 로직에서는 DB에서 카페 이미지가 4개 이상있는지 확인하는데 이 과정에서 `isUsed==false`인 이미지(이미지 삭제 스케줄링에 의해 삭제되지 않은 이미지)까지 카운트합니다. 현재 `isUsed==true`인 이미지만 카운트하도록 로직을 수정했습니다.
- 카페 이미지 3개 초과하는지 판단하는 로직 수정
- 카페 이미지를 3개 초과하여 저장할 시, 예외를 반환하는 테스트 코드가 이미 존재하고 `isUsed`까지 판별하는지 확인하는 테스트 코드가 추가로 필요하지 않다고 생각하여 생략했습니다.
- API 테스트를 통해 제대로 동작하는 지 한 번 더 확인해주세요.
> fix: 카페 이미지 3개 초과하여 저장 시 예외 반환하는 로직 버그 수정

- src/main/java/mocacong/server/service/RefreshTokenService.java
- src/main/resources/application.yml
- 토큰 객체의 TTL은 MILLISECONDS로 설정되어 있음에도 불구하고, redisTemplate을 통해 레디스에 저장할 때 expiration 단위가 SECONDS로 설정되어 있음을 확인했습니다. 로컬에서 검토한 결과, 토큰 객체 자체는 MILLISECONDS로 ttl이 설정되어도 레디스에 저장될 때는 초 단위로 저장됨을 확인하여 이 부분을 수정했습니다.
- expiration 시간 단위를 밀리세컨드 단위로 수정
- 추가적으로 수정해야할 부분이 있는지 확인해주세요
> fix: Token 객체 TTL 시간 단위 이슈 해결

- .github/workflows/ci-backend.yml
- build.gradle
- 모카콩 백엔드 코드를 정적 분석하기 위해 Jacoco 및 SonarCloud를 도입했습니다. 
- 정적 분석 도구로 SonarQube를 선택할 수도 있었지만 SonarQube의 경우, 직접 세팅까지 해야하고 PR 코멘트 또한 유료 기능이라 해서 SonarCloud를 선택했습니다.
- Jacoco 세팅
- SonarCloud 세팅
- CI 스크립트 수정
- 모카콩 QualityGate 기준 
- <img width="300" alt="image" src="https://github.com/mocacong/Mocacong-Backend/assets/69844138/1fb33432-db83-4d1e-a5d3-9c944555adbb">
- 추가적으로 커버리지 영역에서 제외해야 할 클래스가 있다면 알려주세요
- QualityGate 기준을 수정하고 싶은 부분이 있다면 알려주세요
> feat: 코드 정적 분석을 위한 Jacoco 및 SonarCloud 도입

- src/main/java/mocacong/server/config/BatchConfig.java
- src/main/java/mocacong/server/domain/DeletedMember.java
- src/main/java/mocacong/server/repository/DeletedMemberRepository.java
- src/main/java/mocacong/server/service/MemberService.java
- src/test/java/mocacong/server/repository/DeletedMemberRepositoryTest.java
- src/test/java/mocacong/server/repository/MemberRepositoryTest.java
- src/test/java/mocacong/server/service/MemberServiceTest.java
- src/test/resources/application.yml
- 기존의 멤버 삭제는 물리적으로 데이터 베이스에서 삭제하는 작업이었다면, 이제 논리적으로 30일 간 멤버 데이터를 유지하고 삭제합니다. 
- MemberRepositoryTest가 DataJpaTest 어노테이션을 사용하고 있어 Member의 created_at이 null로 지정되어있어 `bulkUpdateStatus`가 정상적으로 진행되지 못했습니다. 이에 어노테이션을 커스텀 RespositoryTest로 변경하고 테스트 로직을 일부 수정했습니다.
- test의 application.yml의 show_sql 속성을 false로 변경해 sql이 두번 중복해서 보이는 문제를 해결했습니다.
- Member 삭제 시 Member 테이블에서는 여전히 물리적으로 삭제하지만, 유저의 정보를 일부 DeletedMember 테이블에 저장합니다.
- 저장되는 정보는 복구 가능성을 배제하고 연관관계 정보를 제외한 이외의 모든 정보로 설정했습니다.
- Scheduled를 사용해 자정에 deletedMember 테이블에서 30일 이상 된 유저를 삭제합니다.
- 스케줄링은 자정마다 `createdTime` 을 기준으로 30일이 지난 회원을 물리적으로 삭제하는 작업을 수행합니다. 로컬에서 테스트하려면 BatchConfig의 시간을 수정해주세요.
- `createdTime`과 `modifiedTime` 중에 고민 후 생성된 날짜 기준이니 `createdTime`으로 결정했는데, `modifiedTime`이 더 나은 것 같다면 말씀해주세요.
- `DeletedMember`테이블은 insert와 delete 작업이 주로 일어나는 …
> feat: 멤버 논리적 삭제 구현

- build.gradle
- 소나클라우드에서 커버리지 측정할 때, exception과 Response에 해당하는 부분들까지 포함하여 측정해서 해당 부분을 제대로 제외하도록 수정했습니다.
- 소나클라우드 커버리지 대상 exclusions 수정
- 이제 exception과 response는 측정에서 제외되는 거로 보이는데 config도 갑자기 측정돼서 이것도 다시 제외되도록 수정은 했습니다.
> fix: 소나클라우드 커버리지 대상 exclusions 범위 수정

- build.gradle
- src/main/java/mocacong/server/support/AwsS3Uploader.java
- 매일 오전 4시 경, 사용하지 않는 이미지를 삭제할 때마다 아래 에러가 발생합니다.
```
ERROR [org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler.handleUncaughtException:39] - Unexpected exception occurred invoking async method: public void mocacong.server.support.AwsS3Uploader.deleteImages(mocacong.server.service.event.DeleteNotUsedImagesEvent)
com.amazonaws.services.s3.model.AmazonS3Exception: The XML you provided was not well-formed or did not validate against our published schema (Service: Amazon S3; Status Code: 400; Proxy: null)
```
**이로 인해, 불필요한 에러 로그가 매일 쌓이고 있습니다.**
(고객 입장에선 문제없지만, 로그 분석하는 데에 불필요한 에러로그가 쌓이는 상황)
- 1,000건 단위로 이미지를 삭제하도록 작업했습니다.
- 리스트 파티셔닝을 위해 Guava 라이브러리를 추가했으며, 버전 선택은 https://mvnrepository.com/artifact/com.google.guava/guava 를 참고했습니다. 
- 로컬에서 S3가 미연동돼있으므로, 그리고 매일 오전 4시에 배치로 작동되는 …
> feat: S3 오브젝트 벌크 삭제 시 1000건 단위로 삭제되도록 변경
